name: Daily City Fuel Prices Scraper

on:
  schedule:
    - cron: '0 6 * * 5'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python city_fuel_prices_scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add -A
        if ! git diff --quiet || ! git diff --staged --quiet; then
          git commit -m "Update city fuel prices data: $(date +'%Y-%m-%d')"
          git pull --rebase origin main
          git push
        fi
