name: Daily Fuel Prices Scraper

on:
  schedule:
    # Uruchamiaj codziennie o 06:00 CET (04:00 UTC)
    - cron: '0 4 * * *'
  workflow_dispatch: # Umożliwia ręczne uruchomienie

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Przyznaj uprawnienia do zapisu zawartości repozytorium
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run scraper
      run: python fuel_prices_scraper.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update fuel prices data: $(date +'%Y-%m-%d')" && git push)
